name: Android CI

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build Android Debug APK and Upload artifact
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Run tests
        run: bash ./gradlew test --stacktrace

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/*.apk